package iot.client;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "MongoException", targetNamespace = "http://manager.iot/")
public class MongoException_Exception extends Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private MongoException faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public MongoException_Exception(String message, MongoException faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public MongoException_Exception(String message, MongoException faultInfo,
			Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean: iot.client.MongoException
	 */
	public MongoException getFaultInfo() {
		return faultInfo;
	}

}
