package iot.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ManagerService service = new ManagerService();
 * ManagerDelegate portType = service.getManagerPort();
 * portType.main(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ManagerService", targetNamespace = "http://manager.iot/", wsdlLocation = "http://localhost:8080/IOTWeb/ManagerPort?wsdl")
public class ManagerService extends Service {

	private final static URL MANAGERSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(iot.client.ManagerService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = iot.client.ManagerService.class.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/IOTWeb/ManagerPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/IOTWeb/ManagerPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		MANAGERSERVICE_WSDL_LOCATION = url;
	}

	public ManagerService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ManagerService() {
		super(MANAGERSERVICE_WSDL_LOCATION, new QName("http://manager.iot/",
				"ManagerService"));
	}

	/**
	 * 
	 * @return returns ManagerDelegate
	 */
	@WebEndpoint(name = "ManagerPort")
	public ManagerDelegate getManagerPort() {
		return super.getPort(new QName("http://manager.iot/", "ManagerPort"),
				ManagerDelegate.class);
	}

}
