package iot.client;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "UnknownHostException", targetNamespace = "http://manager.iot/")
public class UnknownHostException_Exception extends Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private UnknownHostException faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public UnknownHostException_Exception(String message,
			UnknownHostException faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public UnknownHostException_Exception(String message,
			UnknownHostException faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean: iot.client.UnknownHostException
	 */
	public UnknownHostException getFaultInfo() {
		return faultInfo;
	}

}
